proxies:
  - name: ss-undefined-134.255.210.49-989-f8f7aCzcPKbsF8p3-undefined
    server: 134.255.210.49
    type: ss
    country: ğŸ‡¨ğŸ‡¾CY
    port: 989
    password: f8f7aCzcPKbsF8p3
    cipher: aes-256-cfb
  - name: trojan-undefined-35.181.204.0-22222-telegram-id-privatevpns-undefined
    server: 35.181.204.0
    type: trojan
    country: ğŸ‡«ğŸ‡·FR
    port: 22222
    udp: true
    password: telegram-id-privatevpns
    sni: trojan.burgerip.co.uk
    network: tcp
  - name: trojan-undefined-15.236.215.26-22222-telegram-id-privatevpns-undefined
    server: 15.236.215.26
    type: trojan
    country: ğŸ‡«ğŸ‡·FR
    port: 22222
    udp: true
    password: telegram-id-privatevpns
    sni: trojan.burgerip.co.uk
    network: tcp
  - name: ss-undefined-146.70.61.18-8080-14fFPrbezE3HDZzsMOr6-undefined
    server: 146.70.61.18
    type: ss
    country: ğŸ‡¬ğŸ‡§GB
    port: 8080
    password: 14fFPrbezE3HDZzsMOr6
    cipher: rc4-md5
  - name: ss-undefined-217.77.2.244-41747-2ad3daa614b4db4f-undefined
    server: 217.77.2.244
    type: ss
    country: ğŸ‡¬ğŸ‡§GB
    port: 41747
    password: 2ad3daa614b4db4f
    cipher: chacha20-ietf-poly1305
  - name: ss-undefined-45.87.175.181-8080-1RWwXhwfAB5gAEozU4G2Pg-undefined
    server: 45.87.175.181
    type: ss
    country: ğŸ‡±ğŸ‡¹LT
    port: 8080
    password: 1RWwXhwfAB5gAEozU4G2Pg
    cipher: chacha20-ietf-poly1305
  - name: ss-undefined-45.87.175.181-8080-cvII85TrW6n0OGyfpHVS1u-undefined
    server: 45.87.175.181
    type: ss
    country: ğŸ‡±ğŸ‡¹LT
    port: 8080
    password: cvII85TrW6n0OGyfpHVS1u
    cipher: chacha20-ietf-poly1305
  - name: ss-undefined-45.87.175.10-8080-oZIoA69Q8yhcQV8ka3Pa3A-undefined
    server: 45.87.175.10
    type: ss
    country: ğŸ‡±ğŸ‡¹LT
    port: 8080
    password: oZIoA69Q8yhcQV8ka3Pa3A
    cipher: chacha20-ietf-poly1305
  - name: ss-undefined-45.87.175.58-8080-oZIoA69Q8yhcQV8ka3Pa3A-undefined
    server: 45.87.175.58
    type: ss
    country: ğŸ‡±ğŸ‡¹LT
    port: 8080
    password: oZIoA69Q8yhcQV8ka3Pa3A
    cipher: chacha20-ietf-poly1305
  - name: ss-undefined-185.237.185.160-989-f8f7aCzcPKbsF8p3-undefined
    server: 185.237.185.160
    type: ss
    country: ğŸ‡±ğŸ‡¹LT
    port: 989
    password: f8f7aCzcPKbsF8p3
    cipher: aes-256-cfb
  - name: ss-undefined-147.78.1.27-990-f8f7aCzcPKbsF8p3-undefined
    server: 147.78.1.27
    type: ss
    country: ğŸ‡²ğŸ‡½MX
    port: 990
    password: f8f7aCzcPKbsF8p3
    cipher: chacha20-ietf-poly1305
  - name: ss-undefined-193.29.139.189-8080-cvII85TrW6n0OGyfpHVS1u-undefined
    server: 193.29.139.189
    type: ss
    country: ğŸ‡³ğŸ‡±NL
    port: 8080
    password: cvII85TrW6n0OGyfpHVS1u
    cipher: chacha20-ietf-poly1305
  - name: >-
      hysteria2-undefined-31.186.87.211-4029-be758973-186d-46fe-8aa4-e017134fa291-undefined
    server: 31.186.87.211
    type: hysteria2
    country: ğŸ‡µğŸ‡±PL
    port: 4029
    udp: true
    password: be758973-186d-46fe-8aa4-e017134fa291
    sni: www.bing.com
    skip-cert-verify: true
  - name: ss-undefined-217.30.10.18-9003-JdmRK9gMEqFgs8nP-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9003
    password: JdmRK9gMEqFgs8nP
    cipher: aes-256-cfb
  - name: ss-undefined-217.30.10.18-9026-QWDDvVE9npNurQfA-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9026
    password: QWDDvVE9npNurQfA
    cipher: aes-256-cfb
  - name: ss-undefined-217.30.10.18-9037-TN2YqghxeFDKZfLU-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9037
    password: TN2YqghxeFDKZfLU
    cipher: aes-256-cfb
  - name: ss-undefined-217.30.10.18-9059-9XwYyZsK8SNzQDtY-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9059
    password: 9XwYyZsK8SNzQDtY
    cipher: aes-256-cfb
  - name: ss-undefined-217.30.10.18-9033-UTJA57ypk2XKQpnm-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9033
    password: UTJA57ypk2XKQpnm
    cipher: aes-256-cfb
  - name: ss-undefined-217.30.10.18-9014-KnJGad3FqTvjqbaX-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9014
    password: KnJGad3FqTvjqbaX
    cipher: aes-256-cfb
  - name: ss-undefined-217.30.10.18-9060-ueLXVkvh4hckhErQ-undefined
    server: 217.30.10.18
    type: ss
    country: ğŸ‡µğŸ‡±PL
    port: 9060
    password: ueLXVkvh4hckhErQ
    cipher: aes-256-cfb
  - name: trojan-undefined-45.67.215.95-443-tg-fq521free-undefined
    server: 45.67.215.95
    type: trojan
    country: ğŸ‡·ğŸ‡ºRU
    port: 443
    udp: true
    password: tg-fq521free
    sni: torjan.xn--xhq44j.eu.org
    ws-opts:
      path: /
      headers:
        Host: torjan.xn--xhq44j.eu.org
    network: ws
  - name: trojan-undefined-13.51.239.111-22222-telegram-id-privatevpns-undefined
    server: 13.51.239.111
    type: trojan
    country: ğŸ‡¸ğŸ‡ªSE
    port: 22222
    udp: true
    password: telegram-id-privatevpns
    sni: trojan.burgerip.co.uk
    network: tcp
  - name: trojan-undefined-51.20.49.172-22222-telegram-id-privatevpns-undefined
    server: 51.20.49.172
    type: trojan
    country: ğŸ‡¸ğŸ‡ªSE
    port: 22222
    udp: true
    password: telegram-id-privatevpns
    sni: trojan.burgerip.co.uk
    network: tcp
  - name: >-
      hysteria2-undefined-107.167.18.123-443-0aed82ca-fd08-11ef-8cf9-f23c93136cb3-undefined
    server: 107.167.18.123
    type: hysteria2
    country: ğŸ‡ºğŸ‡¸US
    port: 443
    udp: true
    password: 0aed82ca-fd08-11ef-8cf9-f23c93136cb3
    sni: 06a68208-st69s0-su9bm5-1phl.la.shifen.uk
    skip-cert-verify: true
  - name: ss-undefined-45.158.171.141-8080-cvII85TrW6n0OGyfpHVS1u-undefined
    server: 45.158.171.141
    type: ss
    country: ğŸ‡ºğŸ‡¸US
    port: 8080
    password: cvII85TrW6n0OGyfpHVS1u
    cipher: chacha20-ietf-poly1305
  - name: trojan-undefined-visa.cn-443-bpb-trojan-undefined
    server: visa.cn
    type: trojan
    country: ğŸZZ
    port: 443
    udp: true
    password: bpb-trojan
    sni: zamim340.ggff.net
    ws-opts:
      path: /tr?ed=2560
      headers:
        Host: zamim340.ggff.net
    network: ws
  - name: trojan-undefined-japan.com-443-bpb-trojan-undefined
    server: japan.com
    type: trojan
    country: ğŸZZ
    port: 443
    udp: true
    password: bpb-trojan
    sni: zamim340.ggff.net
    ws-opts:
      path: /tr?ed=2560
      headers:
        Host: zamim340.ggff.net
    network: ws
mode: Global
port: 7890
external-controller: 127.0.0.1:9090
